### ISSUE TITLE
Create Metanorma IETF templates

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ietf#1]
Copy over https://github.com/metanorma/rfc-asciirfc-minimal . Should we submodule it or copy it?

ping @opoudjis @abunashir ?

**Comment by opoudjis** [comment]
Copy it. We already know that at least some of the AsciiDoc is going to change in light of the move to Metanorma, to make it consistent with the rest of Metanorma (change from AsciiRFC to Metanorma AsciiDoc, to use your terminology). So the template document is going to change anyway.

**Comment by ronaldtse** [comment]
Done in c3c7623e22ee027b63b02d4d6c1c28aa81977639 .
