### ISSUE TITLE
Add tests to ensure RFC template works

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ietf#2]
https://github.com/metanorma/metanorma-cli/issues/93

Ping @CAMOBAP795

**Comment by CAMOBAP** [comment]
'Local' tests added by https://github.com/metanorma/mn-templates-ietf/pull/3 but there is some problems on windows which need to be investigated

**Comment by CAMOBAP** [comment]
oh, my bad actually this problem was addressed by https://github.com/metanorma/metanorma-ietf/pull/32
