### ISSUE TITLE
Update this repository to metanorma-ietf v2

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-templates-ietf#6]
The Asciidoc markup in this directory needs to be updated to v2 of the gem; see 

https://www.metanorma.com/author/ietf/topics/markup/
https://www.metanorma.com/author/ietf/topics/references/
https://www.metanorma.com/author/ietf/ref/document-attributes/
https://www.metanorma.com/author/ietf/topics/markup-v2tov3/

**Comment by manuelfuenmayor** [comment]
@opoudjis, probably I'm mistaken, but the only updates that I considered necessary were the *anchors  markup* (unless you want me to add additional content to illustrate other markup possibilities). I have pushed a PR in https://github.com/metanorma/mn-templates-ietf/pull/12. Please let me know if I should make any further changes.
Thanks!

**Comment by manuelfuenmayor** [comment]
Task is merged. Closing.
